Update MrmreData.py
the call iteritems to self._feature_types as in self._feature_types.iteritems() produces the error 'AttributeError: 'Series' object has no attribute 'iteritems''

to fix the error and have the program run as intended change iteritems() to items() as in self._feature_types.iteritems() to self._feature_types.items()

each occurrence of iteritems must be changed in order to have the file run as requested.